title: Mathematics Discord Server
description: A place for people to learn and discuss mathematics.
baseurl: ""
url: "https://mathematics.gg/"

github_username:  discord-math

locale: en_US

plugins: []
