title: Mathematics Discord Server
description: A place for people to learn and discuss mathematics.
baseurl: ""
url: "https://mathematics.gg/"

defaults:
  - scope:
      path: ""
    values:
      layout: default

collections_dir: /content

collections:
  books:
    output: true
    permalink: /:collection/:name
    sort_by: title

locale: en_US

plugins: []
